builds:
  - main: ./main
    ldflags:
      - -s -w -X rmux.version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
archives:
  - format: binary
    name_template: rmux
